backend:
  name: git-gateway # open source API that acts as a proxy between authenticated users of your site and your site repo
  branch: master # Branch to update (optional; defaults to master)

# adds an interface for drafting, reviewing, and approving posts
publish_mode: editorial_workflow

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "forms" # Used in routes, e.g., /admin/collections/blog
    label: "Forms" # Used in the UI
    folder: "forms" # The path to the folder where the documents are stored
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
